### ISSUE TITLE
feat: 功能请求

### ISSUE THREAD

**Issue by MapleLeaf2007** [KarinJS/QwQ#5]
## 警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

确保您使用的是 最新开发版本 的 QwQ.
确保您的功能请求尚未在 Issues 列表中提出.
确保您的功能请求是与 QwQ 相关的，且可以实现.

##描述功能

- 去除群聊回复功能的自动at
- 显示当前是否处于消息加密状态
- 跳过扫码五秒确认时间

## 实现方法
请提供您认为可以实现此功能的方法，如果您不知道如何实现，可以留空。
当然，如果您有兴趣，也可以自己实现并向我们提交 Pull Request。

**Comment by callng** [comment]
> * 去除群聊回复功能的自动at

2ed582df463da9c0d0a89dd08d5412ec0fb65b4d 已实现

> * 显示当前是否处于消息加密状态

我不太懂加密，这个需要洛洛来实现 @fuqiuluo 

> * 跳过扫码五秒确认时间

已经包括在 470cbc4eb73383c650b2a0264c192d5609526c10
